 # =============================================================================
 # MCP Variables: Set your account, dataset, datafield and SSC name variables
 # =============================================================================
---
 account: partnertodca.us-4 
 dataset: disharma 
 uid_campaign: Retrieve Attributes Campaign
 promo_campaign: Next Best Promotion Campaign
 promo_datafield: promotions # promos
 uid_datafield: attributes #attributes
