 # =============================================================================
 # MCP Variables: Set your account, dataset, datafield and SSC name variables
 # =============================================================================
---
 account: partnertodca.us-4
 dataset: disharma 
 uid_campaign: Slack User Profile ID Lookup
 promo_campaign: Next Best Action - SST
 promo_datafield: promotions # promos
 uid_datafield: attributes #attributes
